### ISSUE TITLE
Prevent save video flag from causing a bunch of random printouts

### ISSUE THREAD

**Issue by NishanthJKumar** [Learning-and-Intelligent-Systems/predicators_behavior#81]
When we save videos now, the code prints out every single png file that makes up the video frames... This clutters up the terminal. Would be very nice to remove.
@kathrynle20 - if you have time and think this is an easy fix, it'd be great if you could look into this!

**Comment by kathrynle20** [comment]
Created pull request in iGibson repo!

**Comment by NishanthJKumar** [comment]
Awesome, thanks! Merged 😄
